### ISSUE TITLE
PEG SUR TABLETTE

### ISSUE THREAD

**Issue by DEVPEG2024** [DEVPEG2024/PEG_BACKEND#3]
Le PEG est indisponible sur tablette 

404: NOT_FOUND
Code: NOT_FOUND
ID: cdg1::466js-1727441322417-29b171a477c3

**Comment by mguldner** [comment]
Peux-tu ré-essayer ?
Parce que normalement, si le site est accessible sur navigateur PC ou téléphone, il l'est également sur tablette..
Il s'agissait peut-être d'un problème momentané.

**Comment by DEVPEG2024** [comment]
Effectivement ça fonctionne

Cordialement,
